// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'dart:convert' show utf8, base64;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static String _resolveKey(String envName, String fallbackB64) {
    final fromEnv = String.fromEnvironment(envName);
    if (fromEnv.isNotEmpty) return fromEnv;
    return utf8.decode(base64.decode(fallbackB64));
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: _resolveKey('FIREBASE_WEB_API_KEY', 'QUl6YVN5Qzd5YkpWQl94anY1aGJOb081X21BYmRlUmdSREZGQzZZ'),
    appId: '1:668021638019:web:c5dde78b9e796340f3ecb6',
    messagingSenderId: '668021638019',
    projectId: 'aura-living-6885e',
    authDomain: 'aura-living-6885e.firebaseapp.com',
    storageBucket: 'aura-living-6885e.firebasestorage.app',
    measurementId: 'G-JRWR1X9SY9',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: _resolveKey('FIREBASE_ANDROID_API_KEY', 'QUl6YVN5QjYxTV9HdFp5aTRVVFh6LTI3YlVJMU1vQXlTRXJzTmw4'),
    appId: '1:668021638019:android:43e2695f3efc06bef3ecb6',
    messagingSenderId: '668021638019',
    projectId: 'aura-living-6885e',
    storageBucket: 'aura-living-6885e.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: _resolveKey('FIREBASE_IOS_API_KEY', 'QUl6YVN5REIwYnlxbU9oLWZhWUExMW9uR3pCcU5PcWxkaEktV3c0'),
    appId: '1:668021638019:ios:2e21f90911cfdf36f3ecb6',
    messagingSenderId: '668021638019',
    projectId: 'aura-living-6885e',
    storageBucket: 'aura-living-6885e.firebasestorage.app',
    iosBundleId: 'com.auraliving.auraLiving',
  );
}
